PoseFollower3D:
  k_trans: 1.5
  k_rot: 1.25
  max_vel_lin: 0.25
  max_vel_th: 0.3
  min_vel_th: 0.05
  min_in_place_vel_th: 0.0
  in_place_trans_vel: 0.01

  tolerance_trans: 0.2 # 0.02
  tolerance_rot: 0.2
  tolerance_timeout: 0.5

  samples: 4 # for downscaling of traj. in the local planner when there is a collision

  trans_stopped_velocity: 0.005 # if odom reading is slower than this, then robot is stopped
  rot_stopped_velocity: 0.005 # if odom reading is slower than this, then robot is stopped

  transform_tolerance: 0.2
  # for forward simulation to check collisions of local plan:
  sim_time: 1.0
  sim_granularity: 0.2




# from pr2_navigation_config/ local planner. Should not be used by the TrajectoryPlanner in the PoseFollower...


# not used atm:
#  num_traj_steps: 50 # number of steps for trajectory rollouts
#  dt: 0.01 # delta-time on trajectory rollouts
#  dwa: true
  vx_samples: 3
  vtheta_samples: 20
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  occdist_scale: 0.01
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05
  acc_lim_th: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  holonomic_robot: true
