#Independent settings for the planner's costmap
global_costmap: 
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 0.5
  static_map: true
  rolling_window: false
